Crypto-15: Create DetailsScreen
vitalyaliskevych/IosName pull request #8
Opened 2023-01-31 13:42 UTC by vitalyaliskevych

### Whats News
- Create UI from DetailScreen(without graph component)
### Issues
- [Crypto-15](https://trello.com/c/1w82ctqy)
### Screenshot
<img width="217" alt="Screenshot 2023-01-31 at 15 41 39" src="https://user-images.githubusercontent.com/98754902/215776384-6257c35f-3878-4862-a516-b19d1e4f910a.png">

2023-02-03 10:33 UTC, vasyl-nadtochii requested changes
1. Resolve comments
2. The main thing about this screen is that it can accept `CoinInfo` object as a parameter. This object should contain prices (for 5 days), news etc. Please handle that in appropriate way

2023-02-03 10:33 UTC, vasyl-nadtochii commented on Crypto/Extentions/Toolbar.swift
> +            self.toolbar(content: {
bad alignment

2023-02-03 10:33 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +    @ObservedObject var viewModel = DetailViewModel()
add 1 space below and abowe

2023-02-03 10:33 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +                    createButton(text: "Buy Bitcoin", dismissAction: {})
text should be localized
it should accept Coin's name as a parameter
`"Buy [coin]"`

2023-02-03 10:33 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +    var bitcoinPrice: some View {
1. add space above
2. It shouldn't be named `bitcoinPrice`. This screen can accept any coin from list, not only Bitcoin. So it's better to name it `currentPrice`

2023-02-03 10:33 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +                Text("News")
should be localized

2023-02-03 10:33 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +                createToNews(newsModel: newsModel)
`createNewsRow` is better I guess

2023-02-03 10:33 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +            Divider()
for the last news row we need divider to be hidden. Please, handle that

2023-02-03 10:33 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +                }) {
bad alignment

2023-02-03 10:33 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +    func createButton(text: String, dismissAction: (() -> Void)?) -> some View {
1. Better to name `createBuyCoinButton`
2. `dismissAction` ->`action`

2023-02-08 11:30 UTC, vasylnadtochii requested changes
1. Resolve comments
2. Check how `localizedWithVars` works
3. You should have in your view structs only one field - `ViewModel` (it's in general, but some exceptions are also possible). Do not store any other data in your views

2023-02-08 11:30 UTC, vasylnadtochii commented on Crypto/Extentions/Toolbar.swift
> +    func createToolBarDetailView(image: String, text: String, dismissAction: (() -> Void)?) -> some View {
do we need that func?

2023-02-08 11:30 UTC, vasylnadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +                    createBuyCoinButton(text: "buy" + String(" " + coinName.name), action: {})
`text` should be created using `localizedWithVars` func

2023-02-08 11:30 UTC, vasylnadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +                Text("$" + String(format:"%.2f", coinName.price))
create an extension for `Double` which will return formatted price

2023-02-08 11:30 UTC, vasylnadtochii commented on Crypto/Resources/en.lproj/Localizable.strings
> +"buy" = "Buy, %@";
`,` is redundant

2023-02-08 11:30 UTC, vasylnadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +    var coinName: Coin
it should be in `DetailScreenViewModel`

2023-02-08 11:35 UTC, vitalyaliskevych commented on Crypto/Extentions/Toolbar.swift
> +    func createToolBarDetailView(image: String, text: String, dismissAction: (() -> Void)?) -> some View {
yes, we have a toolbar on the screen

2023-02-08 13:06 UTC, vitalyaliskevych commented on Crypto/Extentions/Toolbar.swift
> +    func createToolBarDetailView(image: String, text: String, dismissAction: (() -> Void)?) -> some View {
no, i remoov this

2023-02-13 11:21 UTC, vasyl-nadtochii approved these changes
Please fix last comments and then merge

2023-02-13 11:21 UTC, vasyl-nadtochii commented on Crypto/App/CryptoApp.swift
> +            IntroView()        }
} move to next line

2023-02-13 11:21 UTC, vasyl-nadtochii commented on Crypto/Extentions/Double.swift
> +        return String(format: "%.2f",self)
add space after comma

2023-02-13 11:21 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +                HStack {
do we need this HStack?

2023-02-13 11:21 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailView.swift
> +
remove redundant spaces

2023-02-13 11:21 UTC, vasyl-nadtochii commented on Crypto/Flows/Screens/DetailScreen/DetailViewModel.swift
> +
redundant space

2023-02-13 15:18 UTC, merged